export const PROMO_REQUEST = "PROMO_REQUEST";
export const PROMO_SUCCESS = "PROMO_SUCCESS";
export const PROMO_FAIL = "PROMO_FAIL";

export const NEW_PROMO_REQUEST = "NEW_PROMO_REQUEST";
export const NEW_PROMO_SUCCESS = "NEW_PROMO_SUCCESS";
export const NEW_PROMO_FAIL = "NEW_PROMO_FAIL";

export const PROMO_LIST_REQUEST = "PROMO_LIST_REQUEST";
export const PROMO_LIST_SUCCESS = "PROMO_LIST_SUCCES";
export const PROMO_LIST_FAIL = "PROMO_LIST_FAIL";

export const PROMO_DELETE_REQUEST = "PROMO_DELETE_REQUEST";
export const PROMO_DELETE_SUCCESS = "PROMO_DELETE_SUCCESS";
export const PROMO_DELETE_FAIL = "PROMO_DELETE_FAIL";
